Skipping extracting jmeter

diff --git a/.github/workflows/benchmark.yml b/.github/workflows/benchmark.yml
--- a/.github/workflows/benchmark.yml
+++ b/.github/workflows/benchmark.yml
@@ -55,12 +55,12 @@ jobs:
         docker-compose -f docker-compose_default.yaml up -d
 
 
-    - name: Ensure JMeter is Extracted
-      run: |
-        if [ ! -d .github/tools/apache-jmeter-5.6.2 ]; then
-          echo "Error: JMeter directory is missing in tools. Ensure it's committed to the repository."
-          exit 1
-        fi
+    # - name: Ensure JMeter is Extracted
+    #   run: |
+    #     if [ ! -d .github/tools/apache-jmeter-5.6.2 ]; then
+    #       echo "Error: JMeter directory is missing in tools. Ensure it's committed to the repository."
+    #       exit 1
+    #     fi
           
     - name: Run Benchmark Script
       run: |
